#pragma once

#include <stdio.h>
#include <tchar.h>
#define _USE_MATH_DEFINES
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#define GLEW_STATIC
#include <GL/glew.h>
#include <glut.h>
#include <Windows.h>
#include <GdiPlus.h>
#include <stdexcept>
#include <set>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <fstream>